# Training config for LitOneBarLatentDiffusion

model:
  class_path: experiments.diffusion_prior.lit_ldms.LitPhraseLDM
  init_args:
    model_config:
      sample_size: 68 # 17 * n_bars
      in_channels: 64
      num_layers: 6
      attention_head_dim: 32
      num_attention_heads: 8
      num_key_value_attention_heads: 8
      out_channels: 64
      cross_attention_dim: 128
      time_proj_dim: 64
      global_states_input_dim: 128
      cross_attention_input_dim: 128
    lr: 1e-3
    scale_factor: 1.6484638  # Added scaling factor for constant scaling

# Data module config (example, adjust as needed)
data:
  class_path: datasets.pop909_dataset.POP909DataModule
  init_args:
    jsonl_fp_train: /data1/longshen/Datasets/Piano/POP909/latents/bar_level_pos_seq_64/train_latents.pt
    jsonl_fp_val: /data1/longshen/Datasets/Piano/POP909/latents/bar_level_pos_seq_64/train_latents.pt
    batch_size: 1024
    num_workers: 4
    pin_memory: true
    val_split: 0.1
    dataset_class: POP909OneBarPosLatentDataset
    dataset_kwargs:
      scale: 'constant'
      scaling_factor: 1.6484638
      n_bars: 4
      n_sample: -1  # Use only 1 sample for training

trainer:
  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: /data1/longshen/Results/AccGenResults/diffusion_prior/pos_latent/stable/64d_4bar_allsample
      name: tb_logs
      default_hp_metric: false
  check_val_every_n_epoch: 10 # 50
  log_every_n_steps: 10
  max_epochs: 10000
  accelerator: gpu
  devices: -1
  precision: 32
  gradient_clip_val: 0.5
  default_root_dir: /data1/longshen/Results/AccGenResults/diffusion_prior/pos_latent/stable/64d_4bar_allsample
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 10
        mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        filename: '{epoch}_{step}_{val_loss:.4f}'
        save_last: true


