# S2SVQAE bar-level compression config

model:
  class_path: experiments.bar_compression.LitPhraseAE
  init_args:
    t5_model_name: null  # or "t5-small" if you want to use a pretrained T5
    tokenizer_path: LongshenOu/phrase-vae-tokenizer
    vq_dim: 512 # 512
    vq_codebook_size: 512
    commitment_cost: 0.25
    t5_config: 
      d_model: 512
      d_ff: 1024
      num_layers: 3
      num_heads: 6
      vocab_size: 1000
      decoder_start_token_id: 1
    compress_style: first_n_tokens  # first_token, full_sequence, pooling, first_n_tokens
    n_compress_tokens: 4
    quantize_enc_out: False
    lr: 1e-4

data:
  class_path: datasets.pop909_dataset.POP909DataModule
  init_args:
    jsonl_fp_train: /data1/longshen/Datasets/Piano/POP909/jsonl/pop909_piano_track_bars_train.jsonl
    jsonl_fp_val: /data1/longshen/Datasets/Piano/POP909/jsonl/pop909_piano_track_bars_val.jsonl
    batch_size: 128
    num_workers: 4
    pin_memory: true
    val_split: 0.1
    dataset_class: POP909Dataset
    dataset_kwargs:
      tokenizer_path: LongshenOu/phrase-vae-tokenizer
      max_length: 128
      n_query_tokens: 4

trainer:
  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: /data1/longshen/Results/AccGenResults/bar_compression/s2s/mqcomp/q4_d512_l3_lr1e-4_es20
      name: tb_logs
      default_hp_metric: false
  max_epochs: 1000
  accelerator: gpu
  devices: -1
  log_every_n_steps: 10
  precision: 32
  default_root_dir: /data1/longshen/Results/AccGenResults/bar_compression/s2s/mqcomp/q4_d512_l3_lr1e-4_es20
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_f1_opd
        mode: max
        filename: '{epoch}_{step}_{val_loss:.4f}'
        save_top_k: 3
        save_last: true
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_f1_opd
        mode: max
        patience: 20
        verbose: true
