# Training config for LitOneBarLatentDiffusion

model:
  class_path: experiments.diffusion_prior.lit_ldms.LitPhraseLDM
  init_args:
    model_config:
      sample_size: 256 # 4 * n_bars for now
      in_channels: 128
      num_layers: 12
      attention_head_dim: 32
      num_attention_heads: 8
      num_key_value_attention_heads: 8
      out_channels: 128
      cross_attention_dim: 128
      time_proj_dim: 128
      global_states_input_dim: 128
      cross_attention_input_dim: 128
    mode: 'phr'
    lr: 1e-3
    scale_factor: 2.5321674  # Added scaling factor for constant scaling
    overfit_debug: True
    debug_temp_dir: /home/longshen/work/AccGen/AccGen/temp/phr_latent_debug

# Data module config (example, adjust as needed)
data:
  class_path: datasets.pop909_dataset.POP909DataModule
  init_args:
    jsonl_fp_train: /data1/longshen/Datasets/Piano/POP909/latents/song_level_phr_seq/train_latents.pt
    jsonl_fp_val: /data1/longshen/Datasets/Piano/POP909/latents/song_level_phr_seq/train_latents.pt
    batch_size: 256
    num_workers: 4
    pin_memory: true
    val_split: 0.1
    dataset_class: POP909PhrLatentFixedLenDataset
    dataset_kwargs:
      scaling_factor: 2.5321674
      n_bars: 64
      n_songs: 1
      debug_temp_dir: '/home/longshen/work/AccGen/AccGen/temp/phr_latent_debug'
      batch_size: 256

trainer:
  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: /data1/longshen/Results/AccGenResults/diffusion_prior/phr_latent/64bar/1sample_l12
      name: tb_logs
      default_hp_metric: false
  check_val_every_n_epoch: 50
  log_every_n_steps: 10
  max_epochs: 10000
  accelerator: gpu
  devices: -1
  precision: 32
  gradient_clip_val: 0.5
  default_root_dir: /data1/longshen/Results/AccGenResults/diffusion_prior/phr_latent/64bar/1sample_l12
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: pytorch_lightning.callbacks.ModelSummary
      init_args:
        max_depth: 2
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 10
        mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        filename: '{epoch}_{step}_{val_loss:.4f}'
        save_last: true


